-- ENCRYPT

CREATE COLUMN MASTER KEY KEY_CMK  
WITH (  
     KEY_STORE_PROVIDER_NAME = 'MSSQL_CERTIFICATE_STORE',   
     KEY_PATH = 'Personal/f2260f28d909d21c642a3d8e0b45a830e79a1420'  
   );  

CREATE COLUMN ENCRYPTION KEY KEY_CEK
WITH VALUES  
(  
    COLUMN_MASTER_KEY = KEY_CMK,   
    ALGORITHM = 'RSA_OAEP',   
    ENCRYPTED_VALUE = 0x01700000016C006F00630061006C006D0061006300680069006E0065002F006D0079002F003200660061006600640038003100320031003400340034006500620031006100320065003000360039003300340038006100350064003400300032003300380065006600620063006300610031006300284FC4316518CF3328A6D9304F65DD2CE387B79D95D077B4156E9ED8683FC0E09FA848275C685373228762B02DF2522AFF6D661782607B4A2275F2F922A5324B392C9D498E4ECFC61B79F0553EE8FB2E5A8635C4DBC0224D5A7F1B136C182DCDE32A00451F1A7AC6B4492067FD0FAC7D3D6F4AB7FC0E86614455DBB2AB37013E0A5B8B5089B180CA36D8B06CDB15E95A7D06E25AACB645D42C85B0B7EA2962BD3080B9A7CDB805C6279FE7DD6941E7EA4C2139E0D4101D8D7891076E70D433A214E82D9030CF1F40C503103075DEEB3D64537D15D244F503C2750CF940B71967F51095BFA51A85D2F764C78704CAB6F015EA87753355367C5C9F66E465C0C66BADEDFDF76FB7E5C21A0D89A2FCCA8595471F8918B1387E055FA0B816E74201CD5C50129D29C015895CD073925B6EA87CAF4A4FAF018C06A3856F5DFB724F42807543F777D82B809232B465D983E6F19DFB572BEA7B61C50154605452A891190FB5A0C4E464862CF5EFAD5E7D91F7D65AA1A78F688E69A1EB098AB42E95C674E234173CD7E0925541AD5AE7CED9A3D12FDFE6EB8EA4F8AAD2629D4F5A18BA3DDCC9CF7F352A892D4BEBDC4A1303F9C683DACD51A237E34B045EBE579A381E26B40DCFBF49EFFA6F65D17F37C6DBA54AA99A65D5573D4EB5BA038E024910A4D36B79A1D4E3C70349DADFF08FD8B4DEE77FDB57F01CB276ED5E676F1EC973154F86  
); 


-- CREACION DE TABLAS

CREATE TABLE Roles (
    Id INT 
		IDENTITY NOT NULL PRIMARY KEY,
    Rol NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
);


CREATE TABLE Usuarios (
    Id INT
		IDENTITY NOT NULL PRIMARY KEY,
    Id_Rol INT
		NULL FOREIGN KEY REFERENCES Roles(Id),
    Usuario NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL UNIQUE,
    Nombre NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Primer_Apellido NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Segundo_Apellido NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
    Correo NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Contrasenna NVARCHAR(500)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Pregunta_Seguridad NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Respuesta_Seguridad NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
);

CREATE TABLE Idiomas (
    Id INT
		IDENTITY NOT NULL PRIMARY KEY,
    Idioma NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
);

CREATE TABLE Generos_Peliculas (
    Id INT
		IDENTITY NOT NULL PRIMARY KEY,
    Genero NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
);

CREATE TABLE Peliculas (
    Codigo NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL PRIMARY KEY,
    Id_Genero INT
		NOT NULL FOREIGN KEY REFERENCES Generos_Peliculas(Id),
	Id_Idioma INT
		NOT NULL FOREIGN KEY REFERENCES Idiomas(Id),
    Nombre NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Anno INT
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Actores NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Archivo_Descarga NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
    Archivo_Previsualizacion NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
);

CREATE TABLE Generos_Libros (
    Id INT
		IDENTITY NOT NULL PRIMARY KEY,
    Genero NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
);

CREATE TABLE Libros (
    Codigo NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL PRIMARY KEY,
    Id_Genero INT
		NULL FOREIGN KEY REFERENCES Generos_Libros(Id),
	Id_Idioma INT
		NULL FOREIGN KEY REFERENCES Idiomas(Id),
    Nombre NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Anno INT
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Autores NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Editorial NVARCHAR(100)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Archivo_Descarga NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
    Archivo_Previsualizacion NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
);

CREATE TABLE Generos_Musica (
    Id INT IDENTITY
		NOT NULL PRIMARY KEY,
    Genero NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
);


CREATE TABLE Musica (
    Codigo NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL PRIMARY KEY,
    Id_Genero INT
		NULL FOREIGN KEY REFERENCES Generos_Musica(Id),
	Id_Idioma INT
		NULL FOREIGN KEY REFERENCES Idiomas(Id),
    Nombre NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Anno INT
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Tipo_Interpretacion NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Pais NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Disquera NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Disco NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Compositor NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Archivo_Descarga NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
    Archivo_Previsualizacion NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
);

CREATE TABLE Bitacora (
    Id INT IDENTITY
		NOT NULL PRIMARY KEY,
    Id_Usuario INT
		NULL FOREIGN KEY REFERENCES Usuarios(Id),
	Codigo_Registro NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Tipo NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Descripcion NVARCHAR(500)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Detalle_Registro NVARCHAR(1000)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Fecha DATETIME
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
		-- DEFAULT GETDATE()
);

CREATE TABLE Transacciones (
    Id INT
		IDENTITY NOT NULL PRIMARY KEY,
	Tipo_Pago NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
    Monto DECIMAL
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Fecha DATETIME
		ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
		--DEFAULT GETDATE()
);

CREATE TABLE Descargas (
    Id INT
		IDENTITY NOT NULL PRIMARY KEY,
	Genero NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
    Tipo NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Codigo_Referencia NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Fecha DATETIME
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
		--DEFAULT GETDATE()
);

CREATE TABLE Errores (
    Id INT
		IDENTITY NOT NULL PRIMARY KEY,
	Mensaje NVARCHAR(50)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
    Descripcion NVARCHAR(1000)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Codigo_Error NVARCHAR(30)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Fecha DATETIME
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
		--DEFAULT GETDATE()
);

CREATE TABLE Tarjetas (
    Id INT
		IDENTITY NOT NULL PRIMARY KEY,
	Id_Usuario INT
		NOT NULL FOREIGN KEY REFERENCES Usuarios(Id),
    Numero NUMERIC(20)
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL UNIQUE,
    CVV INT
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
    Tipo NVARCHAR(20)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
    Mes_Expiracion NUMERIC(18,0)
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Anno_Expiracion NUMERIC(18,0)
		ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
);

CREATE TABLE EasyPay (
    Id INT
		IDENTITY NOT NULL PRIMARY KEY,
    Id_Usuario INT
		NOT NULL FOREIGN KEY REFERENCES Usuarios(Id),
    Numero_Cuenta  NUMERIC(20) 
		ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Codigo_Seguridad INT
		ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Contrasenna NVARCHAR(500)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
);

CREATE TABLE Parametros (
    Id INT 
		IDENTITY NOT NULL PRIMARY KEY,
    Codigo NVARCHAR(100)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
    Descripcion NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
    Valor NVARCHAR(1000)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
);

CREATE TABLE Consecutivos (
    Id INT 
		IDENTITY NOT NULL PRIMARY KEY,
    Descripcion NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') 
		NULL,
	Consecutivo NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Posee_Prefijo BIT
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Prefijo NVARCHAR(255)
		COLLATE  Latin1_General_BIN2
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NULL,
	Rango_Inicio INT
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL,
	Rango_Final INT
        ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = KEY_CEK,  ENCRYPTION_TYPE = DETERMINISTIC,  ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
		NOT NULL
);